services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: weather_thesis_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=weather_data
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data

volumes:
  timescale-data: